// --- Core (shared modules) ---
export type {
  PlanStatus,
  Deviation,
  PlanFrontmatter,
  ContractSection,
  PlanContract,
  Plan,
  TrellisConfig,
  ValidationError,
  GateResult,
  RepoEntry,
  ProjectManifest,
  StatusGate,
  TrellisContext,
  GraphData,
  Cycle,
  ChunkPlan,
  ChunkEdge,
  CrossChunkEdge,
  ChunkBoundaryItem,
  Chunk,
  ChunkResult,
  GitExecutor,
  FetchRepoResult,
} from './core/index.ts';

export {
  PlanFile, SECTION_REQUIREMENTS, STATUS_GATES,
  createContext, refreshContext,
  scanPlans, loadConfig, derivePlanId,
  buildGraph, detectCycles, topologicalSort, transitiveDependents,
  computeCriticalPath, pickNext, computeChunks, groupByDirectory,
  groupByTopologicalDepth, chunkContractAggregation, newlyReady,
  parseFrontmatter, validateFrontmatter, readPlanFile, updatePlanFile,
  detectSections, readSection, writeSection, validateStatusGate,
  parseManifest, ensureRemote, fetchRemote, gitShow, gitListTree,
  discoverManifest, fetchRepoPlans, fetchProjectPlans, checkVisibility,
  parseInputs, parseOutputs,
  VALID_STATUSES, filterPlans,
} from './core/index.ts';

// --- High-Level API ---
export { Trellis } from './api.ts';
export type {
  StatusResult,
  PlanSummary,
  BlockedPlanSummary,
  ReadyResult,
  DependencyInfo,
  ShowResult,
  UpdateResult,
  LintIssue,
  LintResult,
  GraphNode,
  GraphEdge,
  GraphResult,
  EpicResult,
  CreateResult,
  CreateOptions,
  SetResult,
  WriteSectionResult,
  ReadSectionResult,
  RenameResult,
  ArchiveResult,
  FetchResult,
  RepoFetchStatus,
  PlanMetric,
  MetricsResult,
} from './api.ts';
